version: '2'
services:
  firestore:
    build: containers/firebase/
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: 'firebase emulators:start'
