version: '2'
services:
  firebase:
    image: docker.pkg.github.com/y-yagi/note-page/note-page_firebase:1.0.1
    container_name: firebase
    ports:
      - '8080:8080'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    command: 'firebase emulators:start'
